spring.application.name=safety-for-people
#spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres

#spring.datasource.username=${DB_USERNAME:postgres}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=postgres.civsmiodbxamacdgxzbi
spring.datasource.password=Nw2LzF2HzIYPwbL6
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/safety_db


postgresql://postgres:[YOUR-PASSWORD]@db.civsmiodbxamacdgxzbi.supabase.co:5432/postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


